default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sequra_user
  password: root
  host: db
  port: 3306

development:
  <<: *default
  database: sequra_development

test:
  <<: *default
  database: sequra_test

production:
  <<: *default
  database: sequra_production
  url: <%= ENV["DATABASE_URL"] %>
  <<: *default
  # database: path/to/persistent/storage/production.sqlite3
